version: "3.8"
services:
  diario-api:
    build: .
    image: diario-api:latest
    container_name: diario-api
    restart: unless-stopped
    ports:
      - "3001:3000"    # host:container -> evita conflito com host 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
